### ISSUE TITLE
Is this compatible with Minecraft NBT data or is it its own format ?

### ISSUE THREAD

**Issue by Wapit1** [alberto-mco/godot_named_binary_tag#1]
I am working on a datapack tool for minecraft and I thought using godot would be a good idea since I already know the program 

thing is I need to be able to pack and unpack NBT files within godot ideally

Is this code able to ?

Thanks

**Comment by alberto-mco** [comment]
This code cannot open a Minecraft NBT file. It was designed based on the idea of the Minecraft NBT file, but the tag identifiers are different. In this case, I use the variable types in Godot Engine as the TagID, not the original ones from the NBT file. Still, it shouldn't be too difficult to adapt the code, since it's based on the same idea for parsing the file. You would need to use the NBT file's TagIDs, change the TagID size from int16 to int8, and probably adjust a few other things.

In any case, here's a link to an article I wrote on CodeProject nine years ago, where I created a .NET library compatible with NBT files.

[NBT File Format](https://www.codeproject.com/Articles/427801/Named-Binary-Tag-serialization)
